In [3]:
import numpy as np

#create a simple array (list)
marks=[10,20,30,40,50]

#create a numpy array
marks_np=np.array([10,20,30,40,50])

marks_np


array([10, 20, 30, 40, 50])

In [5]:
#multidimensional numpy
marks_2=[[10,20,30],[40,50,60],[70,80,90]]
marks_2

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [ ]:
#multidimensional numpy arrays
marks_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
marks_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
#initialise np array with zeros
marks_zeros=np.zeros((3,3))
marks_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#initialise np array with ones
marks_ones=np.ones((5,2))
marks_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
x=np.zeros(4)
x

array([0., 0., 0., 0.])

In [21]:
import math

#initialise an array with random numbers
marks_random=np.random.rand(3,3)
print(marks_random)

marks_random=marks_random*100
marks_random=marks_random.astype(int)
print(marks_random)


marks_random=np.random.randint(1,100,(5,5))
print(marks_random)

[[0.4149446  0.43345472 0.59339447]
 [0.57026113 0.354504   0.93398616]
 [0.01058158 0.9110039  0.14001487]]
[[41 43 59]
 [57 35 93]
 [ 1 91 14]]
[[38 18 66 42 32]
 [63 67 46 40 47]
 [15 70 90 59  6]
 [ 2 56 58 88 39]
 [42 80 62 52  9]]


In [28]:
marks=np.array([10,20,30,40,50])

#accessing elements
print(marks[0])
print(marks[1])

#Adding elements
marks=np.append(marks,60)
print(marks)


marks2=marks[:3]
print(marks2)

marks3=marks[3:]
print(marks3)   

10
20
[10 20 30 40 50 60]
[10 20 30]
[40 50 60]


In [30]:
marks1=np.array([10,20,30])
marks2=np.array([40,50,60])

marks1=marks1*2
print(marks1)

marks3=marks1+marks2
print(marks3)

[20 40 60]
[ 60  90 120]


In [36]:
marks=np.array([10,20,30,40,50])

sum=np.sum(marks)
print(sum)

avg=np.mean(marks)
print(avg)

max=np.max(marks)
print(max)

mean=marks.mean()
print(mean)

sqrt=np.sqrt(marks)
print(sqrt)



150
30.0
50
30.0
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [39]:
marks=np.array([[10,20,30],[40,50,60]])
print(marks)
print(marks.shape)

#reshaping the array
marks=marks.reshape(3,2)
print(marks)

[[10 20 30]
 [40 50 60]]
(2, 3)
[[10 20]
 [30 40]
 [50 60]]


In [ ]:
#flattening the array
marks=np.array([[10,20,30],[40,50,60]])
print(marks)

marks=marks.flatten()
print(marks)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [43]:
#transpose array
#generate 5*2 array
marks=np.random.randint(1,100,(5,2))
print(marks)

#transpose the array
marks=marks.T
print(marks)

[[77 57]
 [34 14]
 [86 14]
 [76 80]
 [10  7]]
[[77 34 86 76 10]
 [57 14 14 80  7]]


In [44]:
#concatenate arrays
marks1=np.array([10,20,30])
marks2=np.array([40,50,60])

marks=np.concatenate((marks1,marks2))
print(marks)

[10 20 30 40 50 60]
